# configuration version: https://roadrunner.dev/docs/intro-config/2.x/en
version: '2.7'

server:
  command: "php rr.php"

http:
  address: "0.0.0.0:9529"
  middleware: [ "static", "gzip"]
  static:
    # root directory for static file (HTTP would not serve .php and .htaccess files).
    dir:   "."
    # list of extensions for forbid for serving.
    forbid: [".php", ".htaccess"]
  # Workers pool settings.
  pool:
    # Debug mode for the pool. In this mode, pool will not pre-allocate the worker. Worker (only 1, num_workers ignored) will be allocated right after the request arrived.
    #
    # Default: false
    debug: false

    # How many worker processes will be started. Zero (or nothing) means the number of logical CPUs.
    #
    # Default: 0
    num_workers: 1

    # Maximal count of worker executions. Zero (or nothing) means no limit.
    #
    # Default: 0
    max_jobs: 0

reload:
  # sync interval
  interval: 1s
  # global patterns to sync
  patterns: [".php"]
  # list of included for sync services
  services:
    http:
      # recursive search for file patterns to add
      recursive: true
      # ignored folders
      ignore: ["vendor", "storage", "tests"]
      # service specific file pattens to sync
      patterns: [".php", ".env"]
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs:     ["."]

logs:
  level: debug