# configuration version: https://roadrunner.dev/docs/beep-beep-config/2.x/en
version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php leevel rr:server"

http:
  address: "0.0.0.0:9527"

static:
  # root directory for static file (HTTP would not serve .php and .htaccess files).
  dir:   "."

  # list of extensions for forbid for serving.
  forbid: [".php", ".htaccess"]

reload:
  # sync interval
  interval: 1s
  # global patterns to sync
  patterns: [".php"]
  # list of included for sync services
  services:
    http:
      # recursive search for file patterns to add
      recursive: true
      # ignored folders
      ignore: ["vendor","storage","tests"]
      # service specific file pattens to sync
      patterns: [".php"]
      # directories to sync. If recursive is set to true,
      # recursive sync will be applied only to the directories in `dirs` section
      dirs:     ["."]

logs:
  level: debug