#!/usr/bin/env php
<?php
// [$QueryPHP] A PHP Framework Since 2010.10.03. <Query Yet Simple>
// ©2010-2017 http://queryphp.com All rights reserved.
<<<queryphp
##########################################################
#   ____                          ______  _   _ ______   #
#  /     \       ___  _ __  _   _ | ___ \| | | || ___ \  #
# |   (  ||(_)| / _ \| '__|| | | || |_/ /| |_| || |_/ /  #
#  \____/ |___||  __/| |   | |_| ||  __/ |  _  ||  __/   #
#       \__   | \___ |_|    \__  || |    | | | || |      #
#     Query Yet Simple      __/  |\_|    |_| |_|\_|      #
#                          |___ /  Since 2010.10.03      #
##########################################################
queryphp;

/**
 * 命名行入口文件
 *
 * @author Xiangmin Liu<635750556@qq.com>
 * @package $$
 * @since 2017.04.28
 * @version 1.0
 */
putenv ( 'queryphp_console=(true)' );
putenv ( 'app_name=~_~@console' );
putenv ( 'controller_name=bootstrap' );
putenv ( 'action_name=index' );
putenv ( 'app_bootstrap=' . __DIR__ . '/vendor/hunzhiwange/framework/src/queryyetsimple/bootstrap/console/bootstrap.php' );
require __DIR__ . '/www/index.php';
