<?php /* 2018-04-04 19:06:02 */ ?>
<?php return array (
  0 => 'Queryyetsimple\\Database\\Console\\Init',
  1 => 'Queryyetsimple\\Database\\Console\\Seedrun',
  2 => 'Queryyetsimple\\Database\\Console\\Migrate',
  3 => 'Queryyetsimple\\Database\\Console\\Create',
  4 => 'Queryyetsimple\\Database\\Console\\Rollback',
  5 => 'Queryyetsimple\\Database\\Console\\Test',
  6 => 'Queryyetsimple\\Database\\Console\\Status',
  7 => 'Queryyetsimple\\Database\\Console\\Breakpoint',
  8 => 'Queryyetsimple\\Database\\Console\\Seedcreate',
  9 => 'Queryyetsimple\\I18n\\Console\\Vue',
  10 => 'Queryyetsimple\\Mvc\\Console\\Controller',
  11 => 'Queryyetsimple\\Mvc\\Console\\Action',
  12 => 'Queryyetsimple\\Mvc\\Console\\Model',
  13 => 'Queryyetsimple\\Queue\\Console\\Work',
  14 => 'Queryyetsimple\\Queue\\Console\\Restart',
  15 => 'Queryyetsimple\\Queue\\Console\\Job',
  16 => 'Queryyetsimple\\Swoole\\Console\\Stop',
  17 => 'Queryyetsimple\\Swoole\\Console\\AutoReload',
  18 => 'Queryyetsimple\\Swoole\\Console\\Server',
  19 => 'Queryyetsimple\\Swoole\\Console\\Restart',
  20 => 'Queryyetsimple\\Swoole\\Console\\Task',
  21 => 'Queryyetsimple\\Swoole\\Console\\Status',
  22 => 'Queryyetsimple\\Swoole\\Console\\Lists',
  23 => 'Queryyetsimple\\Swoole\\Console\\ThriftRpc',
  24 => 'Queryyetsimple\\Swoole\\Console\\Rpc',
  25 => 'Queryyetsimple\\Swoole\\Console\\Close',
); ?>