#!/usr/bin/env php
<?php declare(strict_types=1);
/*
 * This file is part of the ************************ package.
 * _____________                           _______________
 *  ______/     \__  _____  ____  ______  / /_  _________
 *   ____/ __   / / / / _ \/ __`\/ / __ \/ __ \/ __ \___
 *    __/ / /  / /_/ /  __/ /  \  / /_/ / / / / /_/ /__
 *      \_\ \_/\____/\___/_/   / / .___/_/ /_/ .___/
 *         \_\                /_/_/         /_/
 * 
 * The PHP Framework For Code Poem As Free As Wind. <Query Yet Simple>
 * (c) 2010-2018 http://queryphp.com All rights reserved.
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * swoole server 服务状态
 *
 * @author Xiangmin Liu<635750556@qq.com>
 * @package $$
 * @since 2017.12.21
 * @version 1.0
 */
$args = $_SERVER['argv'];
array_shift($args);
array_unshift($args, 'swoole:status');
array_unshift($args, 'leevel');
$_SERVER['argv'] = $args;

require_once dirname(__DIR__) . '/leevel';
