name: static analysis

on:
  push:
  pull_request:

jobs:
  types:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        directory: [app]

    name: Source Code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Run Scripts Before Test
        run: |
          mkdir -p storage/phpstan/cache/nette.configurator

      - name: Execute type checking
        run: php assets/build/phpstan analyse